[".local/share/nvim/site/pack/tpope/opt/sensible"]
type = "git-repo"
url = "https://github.com/tpope/vim-sensible.git"
refreshPeriod = "168h"

[".local/share/nvim/site/pack/tpope/opt/surround"]
type = "git-repo"
url = "https://github.com/tpope/vim-surround.git"
refreshPeriod = "168h"

[".local/share/nvim/site/pack/farmergreg/opt/lastplace"]
type = "git-repo"
url = "https://github.com/farmergreg/vim-lastplace.git"
refreshPeriod = "168h"

[".local/share/nvim/site/pack/ntpeters/opt/better-whitespace"]
type = "git-repo"
url = "https://github.com/ntpeters/vim-better-whitespace.git"
refreshPeriod = "168h"

[".local/share/nvim/site/pack/tpope/opt/sleuth"]
type = "git-repo"
url = "https://github.com/tpope/vim-sleuth.git"
refreshPeriod = "168h"
